### ISSUE TITLE
More servers/change servers

### ISSUE THREAD

**Issue by Foxicity** [ronanPoinsignon/PlayerTracker#1]
Is there a way to change the server it tracks? Thanks

**Comment by Guerinoob** [comment]
Hello, we'll work on this feature, it  should be released in the next few days

**Comment by Foxicity** [comment]
Is there a way that i can change locally by modifying the source code and recompiling?

**Comment by Guerinoob** [comment]
Unfortunately there isn't, the application calls a custom API we've made. We will modify the API and add an option to the application to choose the server for each player, it will probably be released tomorrow

**Comment by Guerinoob** [comment]
The feature has been added in #https://github.com/ronanPoinsignon/PlayerTracker/commit/30a71eec28ae6954a31b984a743d12057ece5650
